import type { Metadata } from "next";
import "../styles/globals.css";
import { Flowbite, ThemeModeScript } from "flowbite-react";
import NavbarContainer from "../containers/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="he" dir="rtl" suppressHydrationWarning>
      <Flowbite>
        <head>
          {/* This script is necessary for dark mode to work */}
          <ThemeModeScript />
        </head>
        <body>
          {/* Navbar with DarkThemeToggle */}
          <NavbarContainer />

          {/* Main content */}
          {children}

          {/* DarkThemeToggle button */}
          <div className="fixed bottom-4 right-4"></div>
        </body>
      </Flowbite>
    </html>
  );
}
